### PR TITLE
fix: handle pod deletion event for non hyperpod case

### LINKED ISSUE #263: Fix remote access cleanup for non-aws pods
```
2025-11-14T21:34:52Z    ERROR   Failed to cleanup SSM managed nodes     {"pod": "workspace-ws-with-access-69f66797d7-ghv5t", "workspace": "ws-with-access", "error": "failed to cleanup activations for pod e793087c-5ebd-45d2-bd9f-dfd0fb6c01ab: failed to describe SSM activations for pod e793087c-5ebd-45d2-bd9f-dfd0fb6c01ab: operation error SSM: DescribeActivations, exceeded maximum number of attempts, 3, get identity: get credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request send failed, Get \"http://169.254.169.254/latest/meta-data/iam/security-credentials/\": dial tcp 169.254.169.254:80: i/o timeout\nfailed to get rate limit token, retry quota exceeded, 0 available, 10 requested"}
github.com/jupyter-ai-contrib/jupyter-k8s/internal/controller.(*PodEventHandler).handlePodDeleted
        /workspace/internal/controller/pod_event_handler.go:196
github.com/jupyter-ai-contrib/jupyter-k8s/internal/controller.(*PodEventHandler).HandleWorkspacePodEvents
        /workspace/internal/controller/pod_event_handler.go:78
sigs.k8s.io/controller-runtime/pkg/handler.(*enqueueRequestsFromMapFunc[...]).mapAndEnqueue
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/handler/enqueue_mapped.go:139
sigs.k8s.io/controller-runtime/pkg/handler.(*enqueueRequestsFromMapFunc[...]).Update
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/handler/enqueue_mapped.go:108
sigs.k8s.io/controller-runtime/pkg/internal/source.(*EventHandler[...]).OnUpdate
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/source/event_handler.go:119
k8s.io/client-go/tools/cache.(*processorListener).run.func1
        /go/pkg/mod/k8s.io/client-go@v0.34.0/tools/cache/shared_informer.go:1074
k8s.io/client-go/tools/cache.(*processorListener).run
        /go/pkg/mod/k8s.io/client-go@v0.34.0/tools/cache/shared_informer.go:1086
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.34.0/pkg/util/wait/wait.go:72
```

TODO - only do remote access cleanup when applicable

### PR DESCRIPTION
**Pull request by aws-prayags**
Fixes #263

### CODE REVIEW

File: internal/controller/pod_event_handler.go [hunk 1]
```diff
@@ -188,13 +194,25 @@ func (h *PodEventHandler) handlePodDeleted(ctx context.Context, pod *corev1.Pod,
...
 	logger.Info("Workspace pod has been deleted", "podUID", pod.UID)
 
-	// Clean up SSM managed nodes for this pod
-	if h.ssmRemoteAccessStrategy == nil {
-		logger.Error(nil, "SSM remote access strategy not available - cannot cleanup SSM managed nodes")
-	} else {
-		if err := h.ssmRemoteAccessStrategy.CleanupSSMManagedNodes(ctx, pod); err != nil {
-			logger.Error(err, "Failed to cleanup SSM managed nodes")
+	// Check if this pod uses SSM remote access strategy by checking labels
+	accessStrategyName := pod.Labels[LabelAccessStrategyName]
```
Comment (JGuinegagne) [inline internal/controller/pod_event_handler.go]: sanity-check: the pod has a label w/ the access strategy?

consider adding inline comment to explain how this label get propagated all the way to the pod.

**Review by henrywa2 — APPROVED** [review]

**Review by aws-jasakshi — APPROVED** [review]
